// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTVH0XBz9IYj9SySCE18UocVU9iR4hHPI',
    appId: '1:239944767220:web:66a53b4a679f40d38270a1',
    messagingSenderId: '239944767220',
    projectId: 'relo-fast',
    authDomain: 'relo-fast.firebaseapp.com',
    storageBucket: 'relo-fast.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdmDg4e9L3hzcz-mROOz8HrNwZlfWGh6Q',
    appId: '1:239944767220:android:416084a3bb6210b88270a1',
    messagingSenderId: '239944767220',
    projectId: 'relo-fast',
    storageBucket: 'relo-fast.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCegVEjIIhmICQUW5s9KlKwVKLDK9WaTbw',
    appId: '1:239944767220:ios:34e923e00c2b7e5f8270a1',
    messagingSenderId: '239944767220',
    projectId: 'relo-fast',
    storageBucket: 'relo-fast.appspot.com',
    iosBundleId: 'com.example.hamaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCegVEjIIhmICQUW5s9KlKwVKLDK9WaTbw',
    appId: '1:239944767220:ios:34e923e00c2b7e5f8270a1',
    messagingSenderId: '239944767220',
    projectId: 'relo-fast',
    storageBucket: 'relo-fast.appspot.com',
    iosBundleId: 'com.example.hamaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTVH0XBz9IYj9SySCE18UocVU9iR4hHPI',
    appId: '1:239944767220:web:f9b1183096a2084f8270a1',
    messagingSenderId: '239944767220',
    projectId: 'relo-fast',
    authDomain: 'relo-fast.firebaseapp.com',
    storageBucket: 'relo-fast.appspot.com',
  );
}
